version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 1
    target-branch: "dev"
    versioning-strategy: increase
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*patternfly*"
      - dependency-name: "*i18next*"
      - dependency-name: "react-router*"
    labels:
      - "build"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 2
    target-branch: "dev"
    labels:
      - "build"
