const TOAST_ADD = 'TOAST_ADD';
const TOAST_REMOVE = 'TOAST_REMOVE';
const TOAST_PAUSE = 'TOAST_PAUSE';
const TOAST_RESUME = 'TOAST_RESUME';
const TOAST_CLEAR = 'TOAST_CLEAR';

export { TOAST_ADD, TOAST_REMOVE, TOAST_PAUSE, TOAST_RESUME, TOAST_CLEAR };
